require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/regions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Region. As you add validations to Region, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {title: 'delhi', country: 'India', currency: 'INR', tax: 5}
  }

  let(:user){
    User.create(email:'test@yopmail.com', password: 'test')
  }

  let(:token){
    JWT.encode({user_id: user.id}, 's3cr3t')
  }

  let(:invalid_attributes) {
    {title: '', country: 'India', currency: 'INR', tax: 5}
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # RegionsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {Authorization: "Bearer #{token}"}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Region.create! valid_attributes
      get regions_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Region" do
        expect {
          post regions_url,
               params: { region: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Region, :count).by(1)
      end

      it "renders a JSON response with the new region" do
        post regions_url,
             params: { region: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Region" do
        expect {
          post regions_url,
               params: { region: invalid_attributes }, as: :json
        }.to change(Region, :count).by(0)
      end

      it "renders a JSON response with errors for the new region" do
        post regions_url,
             params: { region: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested region" do
      region = Region.create! valid_attributes
      expect {
        delete region_url(region), headers: valid_headers, as: :json
      }.to change(Region, :count).by(-1)
    end
  end
end
